### ISSUE TITLE
shouldRotate API could be cleaner

### ISSUE THREAD

**Issue by brentvatne** [yamill/react-native-orientation#1]
Currently I think this is a tad confusing to use - rather than `shouldRotate` could it be `lockToPortrait()`, `lockToLandscape()` and `unlockAllOrientations()`?

**Comment by yamill** [comment]
Agreed. I'll improve the shouldRotate API.

Thanks for the suggestion!

**Comment by tnguyen42** [comment]
By the way... I'm probably lame, but I haven't been able to find out where to lock the orientation. Isn't it supposed to be in the app component?

I have an "undefined is not an object" when trying to evaluate Orientation.shouldRotate.

console.log(Orientation) correctly returns what it should.
Thanks for your help!

**Comment by yamill** [comment]
@tnguyen42 did you put `Orientation.shouldRotate(0);` in the componentDidMount?

**Comment by tnguyen42** [comment]
Yes.

Looks like:
```es6
var Orientation = require('react-native-orientation');

var App = React.createClass({
	componentDidMount: function(){
		Orientation.shouldRotate(0);
  	},
});
```

**Comment by yamill** [comment]
@tnguyen42 in your AppDelegate.m do you have the following? 

```objective-c
- (NSUInteger)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window {
  NSUInteger orientations;

  orientations = UIInterfaceOrientationMaskPortrait;

  if (self.shouldRotate == YES) {
    orientations = UIInterfaceOrientationMaskAllButUpsideDown;
  }

  return orientations;
}

```

Make sure you have the `self.shouldRotate' it used to be `shouldRotate` but was fixed recently.

**Comment by tnguyen42** [comment]
Yeah, everything seems in order. I pasted the code today.
I've just rebuilt the entire app with XCode and it still doesn't work.
Though
```es6
console.log(Orientation);
```
correctly displays ```[tid:com.facebook.React.JavaScript] { shouldRotate: [Function],
  addOrientationListener: [Function],
  removeOrientationListener: [Function] }```

**Comment by tnguyen42** [comment]
Hi,
The function still doesn't work. Am I the only one who encountered such a problem?

**Comment by yamill** [comment]
@tnguyen42 can you post your code somewhere?

**Comment by tnguyen42** [comment]
Well I've just tried to use it on a very short example and I got the same result. So here it is:

```es6
'use strict';

var React = require('react-native');
var SearchPage = require('./SearchPage');

var Orientation = require('react-native-orientation');

var {
	StyleSheet,
	Text,
	Component,
	AppRegistry,
	NavigatorIOS,
	TouchableHighlight,
} = React;

class PropertyFinderApp extends Component {

	componentDidMount () {
		Orientation.shouldRotate(0);
	}

// ------------------------------ Render Here
	render () {

		return (
			<NavigatorIOS
				style={styles.container}
				initialRoute={{
					title: 'Property Finder',
					component: SearchPage,
				}}
			/>
		);
	}
}

var styles = StyleSheet.create({
	text: {
		color: 'black',
		backgroundColor: 'white',
		fontSize: 30,
		margin: 80,
	},
	container: {
		flex: 1,
	},
	button: {
		height: 36,
		flex: 1,
		flexDirection: 'row',
		backgroundColor: '#48BBEC',
		borderColor: '#48BBEC',
		borderWidth: 1,
		borderRadius: 8,
		marginBottom: 10,
		alignSelf: 'stretch',
		justifyContent: 'center',
	},
});

AppRegistry.registerComponent('PropertyFinder', function() {return PropertyFinderApp});
```

**Comment by yamill** [comment]
@tnguyen42 Ok that looks ok. Can you show me your AppDelegate.h + .m files? Also which version of React Native you're using.

**Comment by tnguyen42** [comment]
Hi, thanks for your time.

Here's my AppDelegate.h:
```
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

#import <UIKit/UIKit.h>

@interface AppDelegate : UIResponder <UIApplicationDelegate>

@property (nonatomic) bool shouldRotate;

@property (nonatomic, strong) UIWindow *window;

@end
```

And here's my .m:

```
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

#import "AppDelegate.h"

#import "RCTRootView.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

  /**
   * Loading JavaScript code - uncomment the one you want.
   *
   * OPTION 1
   * Load from development server. Start the server from the repository root:
   *
   * $ npm start
   *
   * To run on device, change `localhost` to the IP address of your computer
   * (you can get this by typing `ifconfig` into the terminal and selecting the
   * `inet` value under `en0:`) and make sure your computer and iOS device are
   * on the same Wi-Fi network.
   */

  jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle"];

  /**
   * OPTION 2
   * Load from pre-bundled file on disk. To re-generate the static bundle
   * from the root of your project directory, run
   *
   * $ react-native bundle --minify
   *
   * see http://facebook.github.io/react-native/docs/runningondevice.html
   */

//   jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"PropertyFinder"
                                                   launchOptions:launchOptions];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [[UIViewController alloc] init];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSUInteger)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window {
  NSUInteger orientations;
  
  orientations = UIInterfaceOrientationMaskPortrait;
  
  if (self.shouldRotate == YES) {
    orientations = UIInterfaceOrientationMaskAllButUpsideDown;
  }
  
  return orientations;
}

@end
```

And my react version is 0.7.1.

**Comment by tnguyen42** [comment]
Issue solved on my part: when adding files to my project, I had to check "Create groups" instead of "Created folder references".
Thanks for your time!

**Comment by yamill** [comment]
@tnguyen42 awesome glad you fixed it!

**Comment by yamill** [comment]
API has been updated @brentvatne :smile: thanks!

**Comment by achang28** [comment]
I tried 1.5 earlier today and could not get ```lockToPortrait()``` to work.  To make things easier for you to see, download both branches (1.4 && 1.5) from the following repo, and ```npm install``` for each branch:  https://github.com/achang28/OrientationTest.

1.4 branch: After pressing the "lock" button in the app, the orientation does in fact lock.
1.5 branch: the orientation does NOT lock after pressing "lock" button...

**Comment by yamill** [comment]
Hey @achang28 Can you try 1.6? Made some minor changes. I'm also looking for someone that can help with getting shouldAutoRotate working.

**Comment by achang28** [comment]
Sure. Will give it a shot in a few hours (currently still in bed...)

**Comment by yamill** [comment]
Cool. Thanks.
From reading the docs it says that the code below should be placed in the view controller.
```objective-c
-(BOOL)shouldAutorotate
{
    return YES;
}
```
I'm just wondering how can this be enabled globally? maybe @brentvatne can help?

**Comment by achang28** [comment]
Unfortunately I have no Obj-C skills...yet.  So with 1.6 ```lockToPortrait``` seems to work fine, whereas  ```lockToLandscape``` isn't behaving correctly -- it continues to allow rotation.

Good job -- keep at it!  Making some progress...
